const config = {
  'SPREADSHEET_ID': 'GOOGLE_SHEETS_SPREADSHEET_ID',
  'CENTER_LAT': 'CENTER_LATITUDE_FOR_MAP',
  'CENTER_LONG': 'CENTER_LONGITUDE_FOR_MAP',
  'MARKER_SCALE' : 'MARKER_SCALE_FOR_MAP'
};